export const url = "https://cricket.sportmonks.com/api/v2.0/";

export const token =
  // "lMmGa2bm5y2SeAH7ih3WKvkPMBU3SuioHrR3vvkqMNc70x2LhLrJrYLs5YVW";
  " MyCwyoiRowolgxtBa8yf50EUKm68smW0dQwgQ5ulspXyfo11pOxZQWCb5TmE";

// token2
//   MyCwyoiRowolgxtBa8yf50EUKm68smW0dQwgQ5ulspXyfo11pOxZQWCb5TmE

// `https://cricket.sportmonks.com/api/v2.0/fixtures/218?api_token=lMmGa2bm5y2SeAH7ih3WKvkPMBU3SuioHrR3vvkqMNc70x2LhLrJrYLs5YVW&include=localteamcount, visitorteamcount, scoreboardscount, runscount, ballscount, stagecount, battingcount, bowlingcount, seasoncount, leaguecount, refereecount, firstumpirecount, secondumpirecount, tvumpirecount, manofmatchcount, manofseriescount, tosswoncount, winnerteamcount, lineupcount, venuecount, oddscount` are not allowed. Allowed include(s) are `localteam, localteamCount, visitorteam, visitorteamCount, localteam.fixtures, localteam.results, visitorteam.fixtures, visitorteam.results, scoreboards, scoreboardsCount, scoreboards.team, runs, runsCount, runs.team, balls, ballsCount, stage, stageCount, balls.team, balls.batsman, balls.bowler, balls.batsmanout, balls.catchstump, balls.score, balls.batsmanone, balls.batsmantwo, batting, battingCount, batting.result, balls.runoutby, batting.team, batting.batsman, batting.bowler, batting.catchstump, batting.batsmanout, batting.runoutby, bowling, bowlingCount, bowling.team, bowling.player, season, seasonCount, league, leagueCount, referee, refereeCount, firstumpire, firstumpireCount, secondumpire, secondumpireCount, tvumpire, tvumpireCount, manofmatch, manofmatchCount, manofseries, manofseriesCount, tosswon, tosswonCount, winnerteam, winnerteamCount, lineup, lineupCount, lineup.team, lineup.player, venue, venueCount, venue.country, odds, oddsCount, odds.bookmaker, odds.market, bowling.bowler, localteam.fixtures.scoreboards, localteam.results.scoreboards, visitorteam.fixtures.scoreboards, visitorteam.results.scoreboards, localteam.fixtures.localteam, localteam.fixtures.visitorteam, visitorteam.fixtures.localteam, visitorteam.fixtures.visitorteam, localteam.results.localteam, localteam.results.visitorteam, visitorteam.results.localteam, visitorteam.results.visitorteam, localteam.country, visitorteam.country`;
